module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['💜', '🌸', '🥰', '💜', '💙', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: '',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: '',
    NEWSLETTER_JID: '120363424740976142@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᴅᴛᴇᴄ ᴍɪɴɪ',
    OWNER_NAME: 'ᴀᴋɪɴᴅᴜ',
    OWNER_NUMBER: '94764703165',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᴅᴛᴇᴄ ᴍɪɴɪ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC6NCl59PwPLJlvGt21',
};
