module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['💜', '🌸', '🥰', '💜', '💙', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: '',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: '',
    NEWSLETTER_JID: '120363424740976142@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '🐼 ᴄʏʙᴇʀ ᴘᴀɴᴅᴀ ᴍᴅ 🐼',
    OWNER_NAME: 'ꜱᴀᴄʜɪᴛʜ',
    OWNER_NUMBER: '+94702782946',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: 'ᴄʏʙᴇʀ x ꜱᴀᴄʜɪʏᴀ',
    CHANNEL_LINK: 'https://chat.whatsapp.com/KySCXYNAz90Im672wK8xyf?mode=gi_t',
};
